### ISSUE TITLE
Can't get Reverse Image Search to work in Milvus 0.6.0

### ISSUE THREAD

**Issue by zacharywhitley** [milvus-io/bootcamp#145]
I haven't had time to dig into why yet. I could be because I didn't set something correctly but the web UI returns an error about not being about to find a counts table or something like that.

**Comment by JackLCL** [comment]
Can you tell us what error the web UI returns?  It would be even better if you could describe in detail your steps and errors.  We need more information to help you solve this problem.

**Comment by zacharywhitley** [comment]
Sorry for not including more info. I put it in at the end of the day and was planning on including it today. I didn't think you'd get back so quickly. :)

I followed the docs at https://github.com/milvus-io/bootcamp/tree/master/EN_solutions/pic_search for a cpu based installation and the related Milvus install at https://github.com/milvus-io/docs/blob/0.6.0/userguide/install_milvus.md

I confirmed that the Milvus install was working correctly by running the example.py file. It worked correctly when using my IP or localhost. 

I'm able to connect to pic_search_demo_web with a browser although after a few seconds I get the following message under "IMAGE SET"

`Error with 'NoneType' object has no attribute 'count_table' images in this set
0/0`

If I add the path to images and hit the '+' it will cycle through the images 1/96, 2/96.....96/96

When I add an original image to match against I don't get any images back. If I look at the logs I can see connections to the web service and I can see that feature vectors are being extracted. I can also see activity in the milvus logs. There don't appear to be any errors or warnings.

**Comment by zacharywhitley** [comment]
Ok, I finally got it running with a correctly configured docker compose file. I think I was having some network issues.

**Comment by kaycn** [comment]
I have the same problem. Can you give me a docker compose file for reference? Thank you

**Comment by ofTheo** [comment]
@zacharywhitley could you share your solution? I am having exactly the same issue. 

On loading the client web gui I immediately get the `Error with 'NoneType' object has no attribute 'count_table'`

I can do the training and see the images being processed but then nothing when I try and match an image, 

My server docker command is: 
```
docker run -d --name zilliz_search_images_demo \
-v /PICS1_FOLDER:/tmp/pic1 \
-v /PICS2_FOLDER:/tmp/pic2 \
-p 35000:5000 \
-e "DATA_PATH=/tmp/images-data" \
-e "MILVUS_HOST=192.168.1.134" \
milvusbootcamp/pic-search-webserver:0.1.0
```
Where the MILVUS_HOST is my local IP address. 

```
docker run --name zilliz_search_images_demo_web \
-d --rm -p 8001:80 \
-e API_URL=http://192.168.1.134:35000 \
milvusbootcamp/pic-search-webclient:0.1.0
```

Here is the gui after loading the images. 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/144000/82714784-13f94080-9c45-11ea-96e4-6c62bdc8ca00.png">

Here is the app.log from the server note the errors connecting 

```
2020-05-22 22:50:32,829 - tensorflow - WARNING - From app.py:31: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2020-05-22 22:50:32,829 - tensorflow - WARNING - From app.py:35: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-05-22 22:50:32,848 - tensorflow - WARNING - From app.py:48: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2020-05-22 22:50:32,872 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

2020-05-22 22:50:33,338 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-05-22 22:50:52,465 - root - ERROR - Fail connecting to server on 192.168.1.134:19530. Timeout
2020-05-22 22:50:52,467 - root - ERROR - 'NoneType' object has no attribute 'count_collection'
2020-05-22 22:50:52,468 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:50:52] "[37mPOST /api/v1/count HTTP/1.1[0m" 200 -
2020-05-22 22:50:54,113 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:50:54] "[37mOPTIONS /api/v1/train HTTP/1.1[0m" 200 -
2020-05-22 22:50:54,118 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:50:54] "[37mPOST /api/v1/train HTTP/1.1[0m" 200 -
2020-05-22 22:50:54,590 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2020-05-22 22:50:54,739 - root - ERROR - [Errno 2] No such file or directory: ''
2020-05-22 22:50:55,138 - app - ERROR - Exception on /api/v1/process [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 105, in thread_status_api
    return "current: {}, total: {}".format(cache['current'], cache['total'])
  File "/usr/local/lib/python3.6/dist-packages/diskcache/core.py", line 1262, in __getitem__
    raise KeyError(key)
KeyError: 'current'
2020-05-22 22:50:55,141 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:50:55] "[35m[1mGET /api/v1/process HTTP/1.1[0m" 500 -
2020-05-22 22:50:59,307 - root - ERROR - Fail connecting to server on 192.168.1.134:19530. Timeout
2020-05-22 22:50:59,307 - root - ERROR - 'NoneType' object has no attribute 'count_collection'
2020-05-22 22:50:59,308 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:50:59] "[37mPOST /api/v1/count HTTP/1.1[0m" 200 -
2020-05-22 22:51:15,449 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:15] "[37mOPTIONS /api/v1/train HTTP/1.1[0m" 200 -
2020-05-22 22:51:17,266 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:17] "[37mPOST /api/v1/train HTTP/1.1[0m" 200 -
2020-05-22 22:51:18,282 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:18] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:19,293 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:19] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:20,307 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:20] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:21,330 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:21] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:22,351 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:22] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:23,361 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:23] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:24,371 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:24] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:25,389 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:25] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:26,407 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:26] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:27,425 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:27] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:28,441 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:28] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:29,465 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:29] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:30,485 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:30] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:31,502 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:31] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:32,525 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:32] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:33,551 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:33] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:34,567 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:34] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:35,583 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:35] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:36,599 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:36] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:37,620 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:37] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:38,640 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:38] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:39,651 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:39] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:40,668 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:40] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:41,680 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:41] "[37mGET /api/v1/process HTTP/1.1[0m" 200 -
2020-05-22 22:51:42,359 - root - ERROR - Fail connecting to server on 192.168.1.134:19530. Timeout
2020-05-22 22:51:42,359 - root - ERROR - 'NoneType' object has no attribute 'has_collection'
2020-05-22 22:51:45,696 - root - ERROR - Fail connecting to server on 192.168.1.134:19530. Timeout
2020-05-22 22:51:45,696 - root - ERROR - 'NoneType' object has no attribute 'count_collection'
2020-05-22 22:51:45,697 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:51:45] "[37mPOST /api/v1/count HTTP/1.1[0m" 200 -
2020-05-22 22:52:26,753 - root - ERROR - Fail connecting to server on 192.168.1.134:19530. Timeout
2020-05-22 22:52:26,875 - root - ERROR - 'NoneType' object has no attribute 'search'
2020-05-22 22:52:26,876 - app - ERROR - Exception on /api/v1/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 136, in do_search_api
    res_id,res_distance = do_search(table_name, file_path, top_k, model, graph, sess)
ValueError: too many values to unpack (expected 2)
2020-05-22 22:52:26,876 - werkzeug - INFO - 172.17.0.1 - - [22/May/2020 22:52:26] "[35m[1mPOST /api/v1/search HTTP/1.1[0m" 500 -
```
